### ISSUE TITLE
[Bug]: Missing Club Details Page

### ISSUE THREAD

**Issue by Maciek99** [miskibin/sejm-stats#22]
### What happened?

There is currently no dedicated club details page on the website, preventing users from accessing detailed information about individual clubs. Additionally, there is inconsistency in the redirection paths:
- In the clubs list, it redirects to `/club/[id]`
- In the envoy's details page, it redirects to `/clubs/[id]`
![image](https://github.com/user-attachments/assets/8fba09be-d4a5-4f7f-a058-d3bf20915d2a)
![image](https://github.com/user-attachments/assets/186dd94e-6081-452f-b0da-97c3649bcb97)

### What type of browser are you seeing the problem on?

Chrome

### Code to produce this issue.

```shell
1. Visit the website.
2. Navigate to any section that lists clubs (e.g., clubs list, envoy's details).
3. Attempt to click on a club to view its details.
```

**Comment by miskibin** [comment]
![127 0 0 1_3000_clubs_Lewica](https://github.com/user-attachments/assets/635640d0-e221-4cfd-b32a-53590f2bac4b)
Thanks, Some ideas what else could be added?

**Comment by Maciek99** [comment]
The clubs logo next to its name at the top would be great
