### ISSUE TITLE
[Bug]: literowka

### ISSUE THREAD

**Issue by ghost** [miskibin/sejm-stats#51]
### What happened?

literowka w 
https://www.sejm-stats.pl/stats -> "Najczęstci adresaci interpelacji"

![image](https://github.com/user-attachments/assets/b3f4ef27-cea3-4f6c-882c-b9f07c7e59cd)

### What type of browser are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by miskibin** [comment]
Dziękuję!
