### ISSUE TITLE
[Feature Request / Suggestion]: Repositioning of the club's logo

### ISSUE THREAD

**Issue by cherryy102** [miskibin/sejm-stats#52]
### Suggestion / Feature Request

I propose moving the club logo to the right side. Then all the logos are in the same position and it looks better.
Before:
![image](https://github.com/user-attachments/assets/d1d07c59-4d7e-4f40-846e-8fbf9f14e7fb)
After:
![image](https://github.com/user-attachments/assets/c2024bac-b794-4db9-9e9c-afefe0b6021d)

**Comment by miskibin** [comment]
Yep. Makes a lot of sense i will modify that
